### PR TITLE
Multiple Configs Support / Enhanced Config Tab

### PR DESCRIPTION
**Pull request by suspectedesp**
Regarding [Issue 24](https://github.com/Skwrr/Dexterion/issues/24) (I was a bit bored lol)
This commit contains a working way of using multiple configs and loading/saving them via Imgui::Combo, seems to be working just fine currently (loading other configs/saving) Debug cout's are still in code code, just commented out

### CODE REVIEW

**Comment by wqq-z** [comment]
Checked. Did test it?

**Comment by suspectedesp** [comment]
Yep, after some bug fixing it worked fine for me on my fork, I always synced with the base so should be fine

**Comment by wqq-z** [comment]
This si sync to the last realese rigth?

**Comment by suspectedesp** [comment]
Correct

**Review by wqq-z — APPROVED** [review]
Aproved

**Review by Skwrr — APPROVED** [review]
Also approved for me, but I'll be still be working on a dynamic config loader.

I.E: Custom config file name, unlimited config file count and config loader from "configs" folder.

**Pull request merged**
